spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwe147..
    driver-class-name: org.postgresql.Driver
data:
    redis:
      host: 127.0.0.1  # 本地Redis地址
      port: 6379       # 默认端口
      database: 0     # 使用第0号数据库

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true